plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.kapt) apply false
}

allprojects {
    repositories {
        maven {
            allowInsecureProtocol = true
            url "https://jitpack.io" }
        mavenCentral()
        google()
        maven{
            allowInsecureProtocol = true
            url 'https://maven.aliyun.com/repository/jcenter'}
        maven {
            allowInsecureProtocol = true
            url 'https://maven.aliyun.com/repository/google' }
        maven {
            allowInsecureProtocol = true
            url 'http://maven.aliyun.com/nexus/content/groups/public/' }
    }

    //加快编译速度不浪费时间
    gradle.taskGraph.whenReady {
        tasks.each { task ->
            if (task.name.contains("Test")) {
                task.enabled = false
            }
        }
    }

    configurations.all {
        resolutionStrategy {
            force 'org.xerial:sqlite-jdbc:3.34.0'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
