plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.kapt)
}

static def releaseTime() {  //获取时间的方法,在Android节点外,另外的节点
    return new Date().format("yyyyMMddHHmm", TimeZone.getDefault())
}

android {
    compileSdkVersion 30
    defaultConfig {
        applicationId "com.blues.app"
        minSdkVersion 26
        targetSdkVersion 30
        versionCode 104
        versionName "1.0.4"
        buildToolsVersion "30.0.3"

        resConfigs "zh"

        ndk { abiFilters 'armeabi', 'armeabi-v7a' }
    }

    //这个是解决lint报错的代码
    lintOptions {
        quiet true
        abortOnError false
        ignoreWarnings true
        checkReleaseBuilds false//方法过时警告的开关
        disable 'InvalidPackage' //Some libraries have issues with this.
        disable 'OldTargetApi' //Lint gives this warning but SDK 20 would be Android L Beta.
        disable 'IconDensities' //For testing purpose. This is safe to remove.
        disable 'IconMissingDensityFolder' //For testing purpose. This is safe to remove.
    }

    sourceSets {
        main {
            manifest.srcFile 'src/main/AndroidManifest.xml'
            java.srcDirs = ['src/main/java']
            aidl.srcDirs = ['src/main/aidl']
            res.srcDirs = ['src/main/res']
            assets.srcDirs = ['src/main/assets']
            jniLibs.srcDir 'src/main/jniLibs'
        }
    }

    buildTypes {
        release {
            debuggable false
            jniDebuggable false
            renderscriptDebuggable false
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

            android.applicationVariants.all {
                variant ->
                    if (variant.buildType.name == 'release') {
                        variant.outputs.all {
                            outputFileName = "BluesApp_${releaseTime()}.apk"
                        }
                    }
            }
        }
    }
    compileOptions {

        sourceCompatibility JavaVersion.VERSION_1_8

        targetCompatibility JavaVersion.VERSION_1_8

    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    //防止aapt工具可能会填充已压缩的PNG文件以加快编译速度
    aaptOptions {
        cruncherEnabled = false
    }
}
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    implementation libs.androidx.multidex
    implementation libs.androidx.appcompat
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.lifecycle.viewmodel
    implementation libs.androidx.lifecycle.livedata
    implementation libs.androidx.lifecycle.runtime
    implementation libs.androidx.core.ktx

    implementation libs.retrofit.core
    implementation libs.okhttp.core
    implementation libs.okhttp.logging.interceptor
    implementation libs.fastjson
    implementation libs.retrofit.converter.gson

    implementation libs.material
    implementation libs.easyrecyclerview
    implementation libs.base.recyclerview.adapter.helper
    implementation libs.smartrefresh.layout
    implementation libs.smartrefresh.header//没有使用特殊Header，可以不加这行
    implementation libs.markdown4j
    implementation libs.androidx.viewpager2

    implementation libs.room.runtime
    implementation libs.room.ktx
    kapt libs.room.compiler

    implementation libs.kotlin.stdlib.jdk8
    implementation libs.kotlinx.coroutines.android

    implementation libs.koin.android
    implementation libs.coil.core
    implementation libs.coil.gif

    implementation libs.ijkplayer.java
    implementation libs.ijkplayer.armv7a
    implementation libs.ijkplayer.arm64
    implementation libs.ijkplayer.exo
    implementation libs.androidx.annotation

//    implementation Glide.glide
//    implementation Glide.compiler

    implementation libs.mmkv.static
    //leakcanary
//    debugImplementation 'com.squareup.leakcanary:leakcanary-android:1.6.1'

    implementation libs.codelocator.core
}
repositories {
    mavenCentral()
}
